### ISSUE TITLE
缺少静态文件

### ISSUE THREAD

**Issue by ZM25XC** [snowykami/gitea-themes#1]
![PixPin_2024-11-13_14-03-36](https://github.com/user-attachments/assets/987019de-f46b-4ddf-a68b-cff1d9a14611)
![image](https://github.com/user-attachments/assets/90bbe194-ac46-4411-aa32-e7540c443d21)

**Comment by snowykami** [comment]
了解了，晚上改一下推送工作流，之前把图片文件夹忽略掉了

**Comment by snowykami** [comment]
诶之前邮件回复没有发送过来。这部分是个特定的logo，可以换成自己的文件或者删掉使用默认值
